language: node_js
services:
  - docker

jobs:
  include:
    - stage: Test
      name: "Backend unit tests"
      node_js:
        - lts/*

      before_install:
        - cd backend

    - name: "Frontend unit tests"
      node_js:
        - lts/*

      before_install:
        - cd frontend

    - stage: Deploy
      name: "Docker push backend"
      before_script:
        - docker login -u "$dockerusername" --password "$dockertoken"
      script:
        - docker build -t teamrtest/rtest backend
      after_script:
        - docker push teamrtest/rtest

    - name: "Docker push frontend"
      before_script:
        - docker login -u "$dockerusername" --password "$dockertoken"
      script:
        - docker build -t teamrtest/rtest-ui frontend
      after_script:
        - docker push teamrtest/rtest-ui

stages:
  - Test
  - name: Deploy
    if: (branch = develop) AND (NOT(type IN (push, pull_request)))
