
os: linux
dist: focal
language: node_js
services:
  - docker

jobs:
  include:
    - name: "Backend unit tests"
      node_js:
        - lts/*

      before_install:
        - cd backend
    
    - name: "Frontend unit tests"
      node_js:
        - lts/*
      
      before_install:
        - cd frontend

#     - name: "Docker"
#       before_script:
#         - docker-compose build
    
#       script:
#         - docker-compose up -d
#         - sleep 1

#       after_script:
#         - docker-compose kill
