language: node_js

jobs:
  include:
    - stage: Test
      name: "Backend unit tests"
      node_js:
        - 14
      before_install:
        - cd backend

    - name: "Frontend unit tests"
      node_js:
        - lts/*

      before_install:
        - cd frontend

stages:
  - name: Test
    if: branch = master
