
jobs:
  include:
    - stage: "Tests"
      language: node_js
    - name: "Backend unit tests"
      node_js:
        - lts/*

      before_install:
        - cd backend
    
    - name: "Frontend unit tests"
      node_js:
        - lts/*
      
      before_install:
        - cd frontend

    - stage: "Deploy"
      services:
      - docker
    - name: "Docker push backend"
      if: branch = master
      before_script:
        - docker login -u "$dockerusername" --password "$dockertoken"
      script:
        - docker build -t teamrtest/rtest backend
      after_script:
        - docker push teamrtest/rtest

    - name: "Docker push frontend"
      if: branch = master
      before_script:
        - docker login -u "$dockerusername" --password "$dockertoken"
      script:
        - docker build -t teamrtest/rtest-ui frontend
      after_script:
        - docker push teamrtest/rtest-ui
