version: '3.7'

services:
  mongo:
    container_name: rtest_db
    networks:
      - backend
    ports:
      - "27017:27017"
    image: mongo:latest

  object_storage:
    container_name: minio
    ports:
    - "9000:9000"
    image: minio/minio
    env_file: 'rtest.env'
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  server:
    container_name: rtest-backend
    networks:
      - backend
      - frontend
    build:
      context: ./backend
      dockerfile: Dockerfile

  client:
    container_name: rtest-frontend
    networks:
      - frontend
    build:
      context: ./frontend
    environment:
      - "CI=true"
    ports:
      - "5000:5000"

networks:
  frontend:
  backend: